[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/DHT sensor library@1.4.6
    adafruit/Adafruit Unified Sensor@1.1.15
    knolleary/PubSubClient@2.8
    paulstoffregen/OneWire@2.3.8
    milesburton/DallasTemperature@3.11.0
    adafruit/Adafruit BMP085 Library@1.2.4
build_flags = -Wall -DAGRI_ENABLE_RS485=1

[env:esp32dev_rs485]
extends = env:esp32dev

[env:esp32dev_scd41]
extends = env:esp32dev
build_flags = -Wall -DAGRI_ENABLE_RS485=1 -DAGRI_ENABLE_SCD41=1

[env:esp32dev_bench]
extends = env:esp32dev
build_flags = -Wall -DAGRI_ENABLE_RS485=1 -DAGRI_ENABLE_SCD41=1
