[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/DHT sensor library@1.4.6
    adafruit/Adafruit Unified Sensor@1.1.15
    knolleary/PubSubClient@2.8
build_flags = -Wall

[env:esp32dev_rs485]
extends = env:esp32dev
build_flags = -Wall -DAGRI_ENABLE_RS485=1
